### ISSUE TITLE
Durable subscription clientID already registered when server crashes

### ISSUE THREAD

**Issue by BuddhiWathsala** [siddhi-io/siddhi-io-nats#16]
**Description:**
Here I tried to use NATS durable subscription. NATS durable subscription takes `durable.name` and `client.id` as a kind of unique identification([Ref](https://nats.io/documentation/streaming/nats-streaming-intro/)). 

In my scenario, the server that siddhi-runner resides crashes unexpectedly and reconcile it after a while. But in the reconciliation, the siddhi-io-nats has thrown an error like below. 
```
[2019-06-06 05:52:20,096] ERROR {io.siddhi.core.stream.input.source.Source} - Error on 'NatsSource-912f17f9-5d61-41e2-aea4-b35021889a1c-1'. Error while connecting to NATS server at destination: MonitorApp_DevicePowerStream Error while connecting at Source 'nats' at 'DevicePowerStream'. Will retry in '5 sec'. io.siddhi.core.exception.ConnectionUnavailableException: Error while connecting to NATS server at destination: MonitorApp_DevicePowerStream
	at io.siddhi.extension.io.nats.source.NATSSource.connect(NATSSource.java:183)
	at io.siddhi.extension.io.nats.source.NATSSource.connect(NATSSource.java:51)
	at io.siddhi.core.stream.input.source.Source.connectWithRetry(Source.java:159)
	at io.siddhi.core.SiddhiAppRuntime.startSources(SiddhiAppRuntime.java:452)
	at io.siddhi.core.SiddhiAppRuntime.start(SiddhiAppRuntime.java:383)
	at io.siddhi.distribution.core.internal.StreamProcessorService.deploySiddhiApp(StreamProcessorService.java:106)
	at io.siddhi.distribution.core.internal.StreamProcessorDeployer.deploySiddhiQLFile(StreamProcessorDeployer.java:92)
	at io.siddhi.distribution.core.internal.StreamProcessorDeployer.deploy(StreamProcessorDeployer.java:292)
	at org.wso2.carbon.deployment.engine.internal.DeploymentEngine.lambda$deployArtifacts$0(DeploymentEngine.java:291)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.wso2.carbon.deployment.engine.internal.DeploymentEngine.deployArtifacts(DeploymentEngine.java:282)
	at org.wso2.carbon.deployment.engine.internal.RepositoryScanner.sweep(RepositoryScanner.java:112)
	at org.wso2.carbon.deployment.engine.internal.RepositoryScanner.scan(RepositoryScanner.java:68)
	at org.wso2.carbon.deployment.engine.internal.DeploymentEngine.start(DeploymentEngine.java:121)
	at org.wso2.carbon.deployment.engine.internal.DeploymentEngineListenerComponent.onAllRequiredCapabilitiesAvailable(DeploymentEngineListenerComponent.java:216)
	at org.wso2.carbon.kernel.internal.startupresolver.StartupComponentManager.lambda$notifySatisfiableComponents$7(StartupComponentManager.java:266)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.wso2.carbon.kernel.internal.startupresolver.StartupComponentManager.notifySatisfiableComponents(StartupComponentManager.java:252)
	at org.wso2.carbon.kernel.internal.startupresolver.StartupOrderResolver$1.run(StartupOrderResolver.java:204)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: java.io.IOException: stan: clientID already registered
	at io.nats.streaming.StreamingConnectionImpl.connect(StreamingConnectionImpl.java:162)
	at io.nats.streaming.StreamingConnectionFactory.createConnection(StreamingConnectionFactory.java:54)
	at io.siddhi.extension.io.nats.source.NATSSource.connect(NATSSource.java:180)
	... 20 more
```
The reason for this error was when server crashes the NATS durable subscription wasn't clean up properly. [This](https://github.com/nats-io/nats-streaming-server/issues/759) was the issue arised in NATS.

**Related Issues:**
https://github.com/nats-io/nats-streaming-server/issues/759

**Comment by mohanvive** [comment]
Tested the scenario with latest NATS version 0.16.0 (and NATS client dependencies) and it works fine. Hence closing the issue.
