### ISSUE TITLE
Issue with NATS client jars

### ISSUE THREAD

**Issue by PrabodDunuwila** [siddhi-io/siddhi-io-nats#22]
**Description:**
The version of jar files put into SiddhiHome/jars have issues. 

**Affected Product Version:**
java-nats-streaming-2.2.2.jar (Add to <SIDDHI_HOME>/jars) , jnats-2.6.5.jar (Add to <SIDDHI_HOME>/jars). When these 2 jars are used it gives an error.

But when using java-nats-streaming-2.2.3.jar , jnats-2.6.0.jar the program works fine.

**Stacktrace of the error:**
`[2019-10-04 19:17:13,820] ERROR {io.siddhi.distribution.editor.core.internal.DebugRuntime} - Siddhi App 'PublishNatsinTextFormat' is in faulty state. io.siddhi.core.exception.SiddhiAppCreationException: Error on 'PublishNatsinTextFormat' @ Line: 51. Position: 21, near '@sink(
	type = 'nats', 
	cluster.id = 'test-cluster',
	destination = 'SweetProduction',
	bootstrap.servers = 'nats://localhost:4222',
	@map(type = 'json'))'. io/nats/streaming/ConnectionLostHandler
	at io.siddhi.core.util.ExceptionUtil.populateQueryContext(ExceptionUtil.java:43)
	at io.siddhi.core.util.parser.helper.DefinitionParserHelper.addEventSink(DefinitionParserHelper.java:588)
	at io.siddhi.core.util.SiddhiAppRuntimeBuilder.defineStream(SiddhiAppRuntimeBuilder.java:119)
	at io.siddhi.core.util.parser.SiddhiAppParser.defineStreamDefinitions(SiddhiAppParser.java:374)
	at io.siddhi.core.util.parser.SiddhiAppParser.parse(SiddhiAppParser.java:230)
	at io.siddhi.core.SiddhiManager.createSiddhiAppRuntime(SiddhiManager.java:85)
	at io.siddhi.core.SiddhiManager.createSiddhiAppRuntime(SiddhiManager.java:95)
	at io.siddhi.distribution.editor.core.internal.DebugRuntime.createRuntime(DebugRuntime.java:202)
	at io.siddhi.distribution.editor.core.internal.DebugRuntime.<init>(DebugRuntime.java:56)
	at io.siddhi.distribution.editor.core.internal.DebugProcessorService.start(DebugProcessorService.java:38)
	at io.siddhi.distribution.editor.core.internal.EditorMicroservice.start(EditorMicroservice.java:759)
	at io.siddhi.distribution.editor.core.internal.EditorMicroservice.startWithVariables(EditorMicroservice.java:779)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invokeResource(HttpMethodInfo.java:187)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invoke(HttpMethodInfo.java:143)
	at org.wso2.msf4j.internal.MSF4JHttpConnectorListener.dispatchMethod(MSF4JHttpConnectorListener.java:218)
	at org.wso2.msf4j.internal.MSF4JHttpConnectorListener.lambda$onMessage$58(MSF4JHttpConnectorListener.java:129)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: io/nats/streaming/ConnectionLostHandler
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.newInstance(Class.java:412)
	at io.siddhi.core.util.SiddhiClassLoader.loadClass(SiddhiClassLoader.java:32)
	at io.siddhi.core.util.SiddhiClassLoader.loadExtensionImplementation(SiddhiClassLoader.java:48)
	at io.siddhi.core.util.parser.helper.DefinitionParserHelper.createSink(DefinitionParserHelper.java:839)
	at io.siddhi.core.util.parser.helper.DefinitionParserHelper.addEventSink(DefinitionParserHelper.java:488)
	... 21 more
Caused by: java.lang.ClassNotFoundException: io.nats.streaming.ConnectionLostHandler cannot be found by siddhi-io-nats_2.0.6
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:398)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:361)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:353)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:161)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 29 more
`

**Comment by pcnfernando** [comment]
Updated the pre-requisite jars in Readme.

- java-nats-streaming-2.2.2.jar (Add to <SIDDHI_HOME>/jars)
- jnats-2.6.5.jar (Add to <SIDDHI_HOME>/jars)
- protobuf-java-3.9.1.jar (Add to <SIDDHI_HOME>/bundles)
